version: "3.8"

services:
    mcp-rust-docs:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: mcp-rust-docs
        restart: unless-stopped
        stdin_open: true
        tty: true
        environment:
            - NODE_ENV=production
            - PORT=27182
        ports:
            - "27182:27182"
        command: ["npm", "run", "start:sse"]
